os:
  - linux

language: php

php:
  - 7.3

service:
  - mysql

before_script:
  - composer self-update
  - composer install --no-interaction
  - mysql -e 'CREATE DATABASE db_catalog'
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

notifications:
  email:
    on_success: never

script:
  - php artisan migrate:fresh
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs -n
